version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - ArsalJavid.pdf
    - babel.html
    - react.html
    - styles/main.css
    - images/*
    - dist/bundle.js
